from .partner_stat import partner_stat
from .persons_stat import persons_stat
from .free_rooms import free_rooms
from .free_after import free_after
from .partners_and_rooms import partners_prefs
from .person_info import persons_info
from .rooms_stat import room_stat
from .hotels_stat import hotels_stat
from .partners_time import partners_times